export var ChannelName = /* @__PURE__ */ ((ChannelName2) => {
  ChannelName2["messageManager"] = "messageManager";
  ChannelName2["threadManager"] = "threadManager";
  ChannelName2["serverManager"] = "serverManager";
  ChannelName2["hackManager"] = "hackManager";
  ChannelName2["targetManager"] = "targetManager";
  ChannelName2["hackConductor"] = "hackConductor";
  ChannelName2["hackScript"] = "hackScript";
  ChannelName2["consoleLink"] = "consoleLink";
  ChannelName2["bootScript"] = "bootScript";
  ChannelName2["shareScript"] = "shareScript";
  return ChannelName2;
})(ChannelName || {});
export var Action = /* @__PURE__ */ ((Action2) => {
  Action2["threads"] = "threads";
  Action2["threadsAvailable"] = "threadsAvailable";
  Action2["getThreads"] = "getThreads";
  Action2["getThreadsAvailable"] = "getThreadsAvailable";
  Action2["freeThreads"] = "freeThreads";
  Action2["updateHost"] = "updateHost";
  Action2["consoleThreadsUse"] = "consoleThreadsUse";
  Action2["lockHost"] = "lockHost";
  Action2["hostLocked"] = "hostLocked";
  Action2["getTotalThreads"] = "getTotalThreads";
  Action2["totalThreads"] = "totalThreads";
  Action2["useShareSwitch"] = "useShareSwitch";
  Action2["hackDone"] = "hackDone";
  Action2["hackReady"] = "hackRead";
  Action2["hackScriptDone"] = "hackScriptDone";
  Action2["weakenScriptDone"] = "weakenScriptDone";
  Action2["growScriptDone"] = "growScriptDone";
  Action2["hackPaused"] = "hackPaused";
  Action2["hackResume"] = "hackResume";
  Action2["printHacks"] = "printHacks";
  Action2["printRunningHacks"] = "printRunningHacks";
  Action2["switchHackMode"] = "switchHackMode";
  Action2["addHost"] = "addHost";
  Action2["getHostList"] = "getHostList";
  Action2["stop"] = "stop";
  Action2["pause"] = "pause";
  Action2["kill"] = "kill";
  Action2["resume"] = "resume";
  Action2["messageRequest"] = "messageRequest";
  Action2["noMessage"] = "noMessage";
  Action2["dumpQueue"] = "dumpQueue";
  Action2["clearMyMessage"] = "clearMyMessage";
  return Action2;
})(Action || {});
